services:
  app:
    image: user-auth-system:latest
    container_name: app
    ports:
      - '5000:5000'
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DB: user_auth
    depends_on:
      - db
    links:
      - db:db

  db:
    image: mysql:8.4.5
    container_name: db
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
