apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-system
  labels:
    app: user-auth-system
spec:
  selector:
    matchLabels:
      app: user-auth-system
  template:
    metadata:
      labels:
        app: user-auth-system
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-auth-system
          image: ywalakamar/user-auth-system:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              cpu: '1'
              memory: 512Mi
          ports:
            - containerPort: 5000

          env:
            - name: FLASK_ENV
              value: development
            - name: MYSQL_HOST
              value: auth-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-system
  labels:
    app: user-auth-system
spec:
  type: NodePort
  selector:
    app: user-auth-system
  ports:
    - port: 8080
      targetPort: 5000
      nodePort: 30000
      protocol: TCP
